const app=document.getElementById('app'); const drawer=document.getElementById('drawer'); const drawerBody=document.getElementById('drawerBody');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=v=>Number(v??0).toLocaleString();
const pill=(v,cls='')=>`<span class="pill ${cls}">${esc(v??'—')}</span>`;
async function api(path){const r=await fetch(path,{cache:'no-store'}); if(!r.ok) throw new Error(`${r.status} ${await r.text()}`); return r.json()}
async function discordPost(action,payload={}){const r=await fetch('/api/discord/action',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-Xianxia-Admin':'1'},body:JSON.stringify({action,payload})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||d.error||`Discord setup action failed (${r.status})`);return d}
async function adminPost(action,payload={}){const r=await fetch('/api/admin/action',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json','X-Xianxia-Admin':'1'},body:JSON.stringify({action,payload})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||d.error||`Admin action failed (${r.status})`);return d}
function resultBox(v,ok=true){return `<div class="result ${ok?'goodbox':'badbox'}"><b>${ok?'Success':'Failed'}</b><pre>${esc(typeof v==='string'?v:JSON.stringify(v,null,2))}</pre></div>`}
function optionRows(rows,value='user_id',label=r=>`${r.name} · ${r.discord_name}`){return rows.map(r=>`<option value="${esc(r[value])}">${esc(label(r))}</option>`).join('')}
function fmtGM(m){m=Number(m||0); const y=Math.floor(m/(60*24*30*12))+1, remY=m%(60*24*30*12), mo=Math.floor(remY/(60*24*30))+1, remM=remY%(60*24*30), d=Math.floor(remM/(60*24))+1; return `Y${y} M${mo} D${d}`}
function table(headers,rows){if(!rows.length)return '<div class="empty">No records.</div>';return `<div class="tablewrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h[0])}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${headers.map(h=>`<td>${typeof h[1]==='function'?h[1](r):esc(r[h[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function timeline(rows){if(!rows.length)return '<div class="empty">No history recorded.</div>';return `<div class="timeline">${rows.map(r=>`<div class="timeline-item"><div>${pill(r.event_type,'purple')} ${pill(`sig ${r.significance}`,'warn')} ${pill(r.visibility)}</div><strong>${esc(r.title)}</strong><div>${esc(r.summary)}</div><div class="timeline-meta">${fmtGM(r.game_minute)} · ${esc(r.location||'Unknown location')} ${r.faction?`· ${esc(r.faction)}`:''}${r.actor_name?` · ${esc(r.actor_name)}`:''}</div></div>`).join('')}</div>`}
function filters(html){return `<div class="filters">${html}<button class="btn" id="applyFilters">Apply</button></div>`}
async function loadOverview(){const d=await api('/api/overview');document.getElementById('worldClock').textContent=d.clock.display;document.getElementById('schema').textContent=`Schema ${d.schema_version} · x${d.clock.scale} time`;const c=d.counts;app.innerHTML=`<div class="cards">${[['Players',c.players],['Living NPCs',c.npcs_alive],['Injured NPCs',c.npcs_injured],['NPC Marriages',c.npc_marriages],['Descendants',c.npc_descendants],['Active Events',c.active_world_events],['Active Battles',c.active_battles],['Active Wars',c.active_wars],['World History',c.world_history],['RAG Memories',c.rag_memories],['Sects',c.sects],['Families',c.birth_families]].map(x=>`<div class="card"><small>${x[0]}</small><div class="metric">${n(x[1])}</div></div>`).join('')}</div><div class="grid2"><div><h2>World Simulation</h2>${table([['System','system'],['Interval',r=>`${n(r.interval_game_minutes)}m`],['Lag',r=>`${n(r.lag_game_minutes)}m`],['Runs','runs']],d.simulations)}</div><div><h2>Current Era</h2><div class="card">${d.active_era?`<h3>${esc(d.active_era.name)}</h3><div>${esc(d.active_era.description||'')}</div><div class="timeline-meta">Started ${fmtGM(d.active_era.started_game_minute)}</div>`:'No active era.'}</div></div></div><h2>Recent Canonical History</h2>${timeline(d.recent_history)}`}
async function loadTimeline(){const d=await api('/api/timeline?limit=150');app.innerHTML=`<h2>Permanent World Timeline</h2>${filters(`<input id="q" placeholder="Search history"><select id="etype"><option value="">All event types</option>${d.event_types.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="vis"><option value="">All visibility</option><option>public</option><option>participant</option><option>faction</option><option>hidden</option></select>`)}<div id="timelineRows">${timeline(d.rows)}</div>`;document.getElementById('applyFilters').onclick=async()=>{const p=new URLSearchParams({limit:'200',q:q.value,event_type:etype.value,visibility:vis.value});const x=await api('/api/timeline?'+p);document.getElementById('timelineRows').innerHTML=timeline(x.rows)}}
async function loadNPCs(){const d=await api('/api/npcs?limit=300&status=alive');app.innerHTML=`<h2>Active NPCs</h2>${filters(`<input id="q" placeholder="Name, job, goal"><select id="loc"><option value="">All locations</option>${d.locations.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="fac"><option value="">All factions</option>${d.factions.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="status"><option>alive</option><option>dead</option><option>all</option></select>`)}<div id="npcRows">${npcCards(d.rows)}</div>`;bindNpc();document.getElementById('applyFilters').onclick=async()=>{const p=new URLSearchParams({limit:'300',q:q.value,location:loc.value,faction:fac.value,status:status.value});const x=await api('/api/npcs?'+p);document.getElementById('npcRows').innerHTML=npcCards(x.rows);bindNpc()}}
function npcCards(rows){return `<div class="npc-grid">${rows.map(r=>`<div class="card npc-card" data-npc="${esc(r.npc_name)}"><h3><span class="status-dot ${r.status==='dead'?'dead':''}"></span>${esc(r.npc_name)}</h3><div class="tagline">${pill(`Realm ${r.realm_index}/${r.phase}`,'blue')}${pill(r.sect_rank||r.faction,'warn')}${r.injury_severity?pill(`Injury ${r.injury_severity}`,'bad'):''}</div><div class="row"><span>Location</span><b>${esc(r.current_location)}</b></div><div class="row"><span>Activity</span><b>${esc(r.activity)}</b></div><div class="row"><span>Mood</span><b>${esc(r.mood||'—')}</b></div><div class="row"><span>Goal</span><b>${esc(r.current_goal||'—')}</b></div><div class="row"><span>Family</span><b>${esc(r.relationship_status||'single')}${r.spouse_name?` · ${esc(r.spouse_name)}`:''}</b></div></div>`).join('')}</div>`}
function bindNpc(){document.querySelectorAll('.npc-card').forEach(el=>el.onclick=()=>showNpc(el.dataset.npc))}
async function showNpc(name){const d=await api('/api/npc?name='+encodeURIComponent(name));const r=d.npc||{};drawerBody.innerHTML=`<h2>${esc(r.npc_name)}</h2><div class="tagline">${pill(r.status)} ${pill(`Realm ${r.realm_index}/${r.phase}`,'blue')} ${pill(r.sect_rank,'warn')} ${r.injury_severity?pill(`Injury ${r.injury_severity}`,'bad'):''}</div><div class="section"><h3>Current life state</h3>${[['Location',r.current_location],['Faction',r.faction],['Profession',r.profession],['Activity',r.activity],['Mood',r.mood],['Goal',r.current_goal],['Goal progress',`${r.goal_progress||0}%`],['Health',r.health],['Injury',r.injury||'None'],['Spouse',r.spouse_name||'None'],['Children',r.children_count||0]].map(x=>`<div class="row"><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join('')}</div><div class="section"><h3>Social relations</h3>${table([['NPC A','npc_a'],['NPC B','npc_b'],['Type','relation_type'],['Affinity','affinity'],['Trust','trust'],['Grudge','grudge']],d.social)}</div><div class="section"><h3>Master / disciple</h3>${table([['Master','master_name'],['Disciple','disciple_name'],['Status','status'],['Reason','reason']],d.disciples)}</div><div class="section"><h3>Descendants</h3>${table([['Child','child_name'],['Parent A','parent_a'],['Parent B','parent_b'],['Root','spiritual_root'],['Status','status']],d.descendants)}</div><div class="section"><h3>Canonical history</h3>${timeline(d.history)}</div><details><summary>GM-only canonical NPC definition</summary><div class="code">${esc(JSON.stringify(d.gm_definition,null,2))}</div></details>`;drawer.classList.remove('hidden')}
async function loadFamilies(){const d=await api('/api/families');const byFam=(arr,id)=>arr.filter(x=>Number(x.family_id)===Number(id));app.innerHTML=`<h2>Birth Families & Clan Politics</h2><div class="family-grid">${d.birth_families.map(f=>`<div class="card family-card"><h3>${esc(f.family_name)}</h3><div class="tagline">${pill(f.archetype)} ${pill(`Tier ${f.tier}`,'warn')} ${pill(f.line_status,f.line_status==='active'?'good':'bad')}</div><div class="row"><span>Head</span><b>${esc(f.head_title)} ${esc(f.head_name)}</b></div><div class="row"><span>Location</span><b>${esc(f.location)}</b></div><div class="row"><span>Wealth / Influence</span><b>${n(f.wealth)} / ${n(f.influence)}</b></div><div class="row"><span>Bloodline</span><b>${esc(f.bloodline_name)} (${n(f.bloodline_purity)}%)</b></div><div class="row"><span>Branches / Retainers</span><b>${n(f.branch_count)} / ${n(f.retainer_count)}</b></div><details><summary>Family tree</summary><div class="section"><b>Player line</b>${byFam(d.birth_family_players,f.family_id).map(x=>`<div>• ${esc(x.name)} · Realm ${x.realm_index}/${x.phase}</div>`).join('')||'<div class="muted">No player character.</div>'}</div><div class="section"><b>NPC relatives</b>${byFam(d.birth_family_npcs,f.family_id).map(x=>`<div>• ${esc(x.relation)} — ${esc(x.name)} (${esc(x.status)})</div>`).join('')||'<div class="muted">None.</div>'}</div><div class="section"><b>Branches</b>${byFam(d.clan_branches,f.family_id).map(x=>`<div>• ${esc(x.branch_name)} — ${esc(x.leader_name)} · strength ${x.martial_strength}</div>`).join('')||'<div class="muted">None.</div>'}</div></details></div>`).join('')}</div><h2>Player-Founded Families</h2>${table([['Family','name'],['Founder','founder_name'],['ID','family_id']],d.player_families)}<h2>Autonomous NPC Marriages & Descendants</h2>${table([['NPC','npc_name'],['Spouse','spouse_name'],['Children','children_count'],['Rank','sect_rank']],d.npc_marriages)}${table([['Child','child_name'],['Parent A','parent_a'],['Parent B','parent_b'],['Root','spiritual_root'],['Realm',r=>`${r.realm_index}/${r.phase}`],['Status','status']],d.npc_descendants)}`}
async function loadSects(){const d=await api('/api/sects');app.innerHTML=`<h2>Sect Politics</h2><div class="sect-grid">${d.sects.map(s=>`<div class="card sect-card"><h3>${esc(s.sect_name)}</h3><div class="tagline">${pill(s.alignment)} ${pill(s.specialty,'blue')}</div><div class="row"><span>Influence</span><b>${s.influence}</b></div><div class="bars"><span style="width:${Math.max(0,Math.min(100,s.influence))}%"></span></div><div class="row"><span>Cohesion / Resources</span><b>${s.cohesion} / ${s.resources}</b></div><div class="row"><span>Recruitment / Doctrine</span><b>${s.recruitment_pressure} / ${s.doctrine_pressure}</b></div><div class="row"><span>Policy</span><b>${esc(s.leader_policy)}</b></div><div class="row"><span>Players / NPCs</span><b>${s.player_members} / ${s.npc_members}</b></div><div class="row"><span>Prestige / Treasury</span><b>${n(s.prestige)} / ${n(s.treasury_stones)}</b></div></div>`).join('')}</div><h2>Internal Factions</h2>${table([['Sect','sect_name'],['Faction','faction_name'],['Agenda','agenda'],['Power','power'],['Loyalty','loyalty']],d.factions)}<h2>Inter-Sect Relations</h2>${table([['Sect A','sect_a'],['Sect B','sect_b'],['Score','relation_score'],['Type','relation_type'],['Treaty','treaty_status']],d.relations)}<h2>Recent Political Developments</h2>${table([['Sect','sect_name'],['Event','event_text'],['Severity','severity'],['Time',r=>fmtGM(r.game_minute)]],d.events)}`}
async function loadConflicts(){const d=await api('/api/conflicts');app.innerHTML=`<h2>Territorial Wars</h2>${table([['ID','war_id'],['Territory','territory_name'],['Attacker','attacker_key'],['Defender','defender_key'],['Status','status'],['Score',r=>`${r.attacker_score} : ${r.defender_score}`],['Siege','siege_progress'],['Resolution','resolution']],d.wars)}<h2>Battles</h2>${table([['Player','player_name'],['Opponent','npc_name'],['Location','location'],['Source','source'],['Status','status'],['HP',r=>`${r.player_hp}/${r.player_hp_max} vs ${r.npc_hp}/${r.npc_hp_max}`],['Outcome','final_outcome']],d.battles)}<h2>NPC Feuds</h2>${table([['NPC A','npc_a'],['NPC B','npc_b'],['Type','relation_type'],['Grudge','grudge'],['Affinity','affinity'],['Trust','trust']],d.npc_feuds)}<h2>Player Grudges & Bounties</h2>${table([['Player','player_name'],['Holder',r=>`${r.holder_type}:${r.holder_key}`],['Intensity','intensity'],['Reason','reason']],d.player_grudges)}${table([['Player','player_name'],['Amount','amount'],['Reason','reason'],['Hunter','hunter_name'],['Pursuit','pursuit_status'],['Pressure','pressure']],d.bounties)}<h2>Boss Encounters</h2>${table([['Boss','boss_name'],['Location','location'],['Status','status'],['HP',r=>`${r.boss_hp}/${r.boss_hp_max}`],['Round','round_index'],['Phase','phase_index']],d.bosses)}`}
async function loadEvents(){const d=await api('/api/events');app.innerHTML=`<h2>World Events</h2>${table([['Title','title'],['Type','event_type'],['Location','location'],['Active',r=>pill(r.active?'ACTIVE':'closed',r.active?'good':'muted')],['Ends',r=>new Date(Number(r.ends_at)*1000).toLocaleString()]],d.world_events)}<h2>Regional Civilization State</h2>${table([['Location','location'],['World','world_name'],['Population',r=>n(r.population)],['Prosperity','prosperity'],['Security','security'],['Resources','spirit_resources'],['Food','food_supply'],['Migration','migration_pressure'],['Unrest','unrest']],d.regions)}<h2>Recent Regional Incidents</h2>${table([['Location','location'],['Event','event_text'],['Severity','severity'],['Time',r=>fmtGM(r.game_minute)]],d.civilization_events)}<h2>World Eras</h2>${table([['Era','name'],['Description','description'],['Active',r=>r.active?'Yes':'No'],['Started',r=>fmtGM(r.started_game_minute)]],d.eras)}`}
async function loadPlayers(){const d=await api('/api/players');app.innerHTML=`<h2>Players</h2>${table([['Name','name'],['Discord','discord_name'],['Life','life_status'],['Realm',r=>`${r.realm_index}/${r.phase}`],['Body',r=>`${r.body_realm_index}/${r.body_phase}`],['Location','location'],['Sect',r=>r.sect_name?`${r.sect_name} · ${r.rank_name}`:'Independent'],['Vitality',r=>`${r.vitality}/${r.vitality_max}`],['Qi',r=>`${r.qi}/${r.qi_max}`],['Karma','karma_score'],['Memories','memory_count']],d.players)}<h2>Recent Player World Actions</h2>${table([['Player','player_name'],['Action','action_type'],['Target',r=>`${r.target_type}:${r.target_key}`],['Location','location'],['Severity','severity'],['Time',r=>fmtGM(r.game_minute)]],d.recent_actions)}<h2>Scene Activity</h2>${table([['Player','player_name'],['Messages','player_messages'],['Last Scene','last_scene_id'],['Last Real Time',r=>r.last_scene_at?new Date(Number(r.last_scene_at)*1000).toLocaleString():'—']],d.scene_activity)}`}
async function loadRag(){const d=await api('/api/rag?limit=200');app.innerHTML=`<h2>RAG Memory Inspector</h2><div class="cards"><div class="card"><small>Player memories</small><div class="metric">${n(d.memories.length)}</div></div><div class="card"><small>Safe canon documents</small><div class="metric">${n(d.canon_count)}</div></div><div class="card"><small>World-history events</small><div class="metric">${n(d.history_count)}</div></div></div>${filters(`<input id="q" placeholder="Search memory"><select id="uid"><option value="">All players</option>${d.players.map(x=>`<option value="${x.user_id}">${esc(x.name)}</option>`).join('')}</select><input id="npc" placeholder="NPC exact name">`)}<div id="ragRows">${ragTable(d.memories)}</div>`;document.getElementById('applyFilters').onclick=async()=>{const p=new URLSearchParams({limit:'250',q:q.value,user_id:uid.value,npc:npc.value});const x=await api('/api/rag?'+p);document.getElementById('ragRows').innerHTML=ragTable(x.memories)}}
function ragTable(rows){return table([['Player','player_name'],['Kind','memory_kind'],['Summary','summary'],['Salience','salience'],['Location','location'],['NPC','npc_name'],['Source','source'],['Time',r=>fmtGM(r.game_minute)],['Recalls','recalled_count']],rows)}
async function loadDecisions(){const d=await api('/api/decisions?limit=250');app.innerHTML=`<h2>Autonomous NPC Decisions</h2>${table([['NPC','npc_name'],['Status','status'],['Location','current_location'],['Faction','faction'],['Rank','sect_rank'],['Activity','activity'],['Mood','mood'],['Goal','current_goal'],['Progress',r=>`${r.goal_progress}%`],['Recent autonomous development','recent_event']],d.minds)}<h2>Autonomous Outcomes Written to History</h2>${timeline(d.history)}<h2>Simulation Clocks</h2>${table([['System','system'],['Last minute','last_game_minute'],['Interval','interval_game_minutes'],['Runs','runs']],d.simulation)}`}

async function loadDiscordSetup(){
 const d=await api('/api/discord');
 if(!d.control_available){app.innerHTML=`<h2>Discord Server Setup</h2><div class="card badbox"><b>Discord bot control is unavailable.</b><div class="muted">${esc(d.message||'The dashboard cannot reach the Python Discord bot.')}</div></div>`;return}
 const guild=d.guild||{}, bot=d.bot||{}, perms=d.permissions||[], base=d.base_channels||[], realms=d.realm_hubs||[], channels=d.text_channels||[];
 const pgood=perms.filter(x=>x.ok).length;
 const channelOptions=current=>channels.map(c=>`<option value="${c.id}" ${Number(current)===Number(c.id)?'selected':''}>#${esc(c.name)} · ${esc(c.category)}</option>`).join('');
 const byKey=Object.fromEntries(base.map(x=>[x.key,x]));
 const bind=(id,label,key)=>`<label>${label}<select id="${id}"><option value="">Keep current</option>${channelOptions(byKey[key]?.channel_id||byKey[key]?.configured_id)}</select></label>`;
 app.innerHTML=`<div class="admin-hero"><div><div class="eyebrow">DISCORD SERVER CONTROL</div><h2>Xianxia RP Discord Setup</h2><p>The dashboard talks to the connected Python bot. Discord.py creates/repairs channels and roles; Go remains responsible only for canonical game state.</p></div><div class="tagline">${pill(guild.name||'Guild','good')}${pill(`${pgood}/${perms.length} permissions`,pgood===perms.length?'good':'warn')}${pill(`${d.registered_commands||0} commands`,'blue')}</div></div>
 <div id="discordResult"></div>
 <div class="cards">
  <div class="card"><small>Connected Guild</small><div class="metric">${esc(guild.name||'—')}</div><div class="muted">${esc(guild.id||'')}</div></div>
  <div class="card"><small>Base Channels</small><div class="metric">${n(d.base_ready)}/${n(d.base_total)}</div></div>
  <div class="card"><small>Realm Hubs</small><div class="metric">${n(d.realm_ready)}/${n(d.realm_total)}</div></div>
  <div class="card"><small>Setup State</small><div class="metric ${d.setup_ready?'good':'warn'}">${d.setup_ready?'READY':'ATTENTION'}</div></div>
 </div>
 <div class="admin-grid">
  <section class="card control"><h3>🛠️ Automatic Setup</h3><p>Safe and idempotent. Existing configured/name-matching channels are reused and repaired.</p><div class="buttonrow"><button class="btn primary" id="fullSetup">Full Setup</button><button class="btn" id="repairSetup">Repair Server</button><button class="btn" id="refreshDiscord">Refresh Status</button></div><div class="buttonrow"><button class="btn" id="syncCommands">Sync Slash Commands</button><button class="btn" id="syncRealmRoles">Sync Realm Roles</button><button class="btn" id="rebuildInfo">Rebuild Info Guide</button><button class="btn" id="testAnnouncement">Test Announcement</button></div></section>
  <section class="card control"><h3>🔐 Permission Diagnostics</h3>${perms.map(x=>`<div class="row"><span>${esc(x.label)}</span><b class="${x.ok?'good':'bad'}">${x.ok?'READY':'MISSING'}</b></div><div class="muted">${esc(x.purpose)}</div>`).join('')}${(d.permission_warnings||[]).length?`<div class="result badbox"><b>Attention</b><div>${(d.permission_warnings||[]).map(x=>`• ${esc(x)}`).join('<br>')}</div></div>`:''}</section>
 </div>
 <div class="grid2">
  <section><h2>Base Xianxia RP Channels</h2>${table([['Channel','key'],['State',r=>pill(r.status,r.status==='ready'?'good':r.status==='stale'?'bad':'warn')],['Discord Channel',r=>r.name?`#${esc(r.name)} · ${r.channel_id}`:'—']],base)}</section>
  <section><h2>Realm Capitals</h2>${table([['World','world'],['State',r=>pill(r.ready?'ready':'missing',r.ready?'good':'warn')],['Channel',r=>r.channel_name?`#${esc(r.channel_name)}`:'—'],['Role',r=>esc(r.role_name||'—')]],realms)}</section>
 </div>
 <h2>Use Existing Channels</h2><section class="card control"><p>Choose existing text channels instead of the recommended generated layout. Blank selections preserve the current binding.</p><div class="grid2">${bind('bindAnnouncements','World events / announcements','world-events')}${bind('bindScenes','Event scenes','event-scenes')}${bind('bindHomes','Player homes','player-homes')}${bind('bindLogs','Bot logs','bot-logs')}${bind('bindBegin','Begin here','begin-here')}${bind('bindInfo','Xianxia info','xianxia-info')}${bind('bindExploration','Expeditions','expeditions')}</div><label>Audit reason<input id="discordReason" value="GM dashboard Discord setup"></label><button class="btn primary" id="saveBindings">Save Channel Bindings</button></section>`;
 const out=document.getElementById('discordResult');
 const run=async(action,payload={},confirmText='')=>{if(confirmText&&!confirm(confirmText))return;out.innerHTML='<div class="loading">Applying Discord setup action…</div>';try{const r=await discordPost(action,{...payload,reason:discordReason?.value||'GM dashboard Discord setup'});out.innerHTML=resultBox(r.result??r);setTimeout(()=>loadDiscordSetup().catch(()=>{}),900)}catch(e){out.innerHTML=resultBox(e.message,false)}};
 fullSetup.onclick=()=>run('setup',{},'Install/repair the recommended Xianxia RP Discord layout and sync slash commands?');
 repairSetup.onclick=()=>run('repair',{},'Repair Xianxia RP channels, permissions, realm roles and slash commands?');
 refreshDiscord.onclick=()=>loadDiscordSetup();
 syncCommands.onclick=()=>run('sync_commands');
 syncRealmRoles.onclick=()=>run('sync_roles');
 rebuildInfo.onclick=()=>run('rebuild_info');
 testAnnouncement.onclick=()=>run('test_announcement',{},'Send a visible Xianxia RP dashboard test message to the configured world-events channel?');
 saveBindings.onclick=()=>run('bind_channels',{announcements:bindAnnouncements.value,scenes:bindScenes.value,homes:bindHomes.value,logs:bindLogs.value,begin:bindBegin.value,info:bindInfo.value,exploration:bindExploration.value},'Save these Discord channel bindings?');
}

async function loadAdmin(){
 const d=await api('/api/admin');
 if(!d.enabled){app.innerHTML=`<h2>Admin Console</h2><div class="card warnbox"><b>Admin writes are disabled.</b><div class="muted">Set DASHBOARD_ADMIN_WRITES=true and GAME_ENGINE_URL to enable authoritative controls.</div></div>`;return}
 const players=d.players||[], sims=d.simulations||[], automation=d.automation||{};
 const pOpts=optionRows(players), locations=(d.locations||[]).map(x=>`<option>${esc(x)}</option>`).join(''), currencies=(d.currencies||[]).map(x=>`<option>${esc(x)}</option>`).join('');
 const db=d.database||{}, pragmas=db.pragmas||{};
 app.innerHTML=`<div class="admin-hero"><div><div class="eyebrow">AUTHORITATIVE GO CONTROL PLANE</div><h2>GM Admin Console</h2><p>All mutations are executed by the Go engine and written to the canonical SQLite WAL database. Dangerous actions require confirmation and are audit logged.</p></div><div class="tagline">${pill(pragmas.journal_mode||'DB','good')}${pill(`FK ${pragmas.foreign_keys??'?'}`,'blue')}${pill(`${players.length} players`,'warn')}</div></div>
 <div id="adminResult"></div>
 <div class="admin-grid">
  <section class="card control"><h3>⏳ World Time</h3><p>Advance or rewind canonical game time.</p><label>Minutes<input id="timeMinutes" type="number" value="1440"></label><label>Reason<input id="timeReason" value="GM world adjustment"></label><button class="btn primary" id="advanceTime">Apply time change</button></section>
  <section class="card control"><h3>⚙️ Simulation</h3><p>Force a native Go batch or change its interval.</p><label>System<select id="simSystem">${sims.map(x=>`<option>${esc(x.system)}</option>`).join('')}</select></label><div class="fieldrow"><label>Steps<input id="simSteps" type="number" min="1" max="120" value="1"></label><label>Interval days<input id="simDays" type="number" min="1" max="365" value="1"></label></div><div class="buttonrow"><button class="btn" id="forceSim">Force batch</button><button class="btn" id="setInterval">Set interval</button></div></section>
  <section class="card control"><h3>🧭 Teleport Player</h3><label>Player<select id="telePlayer">${pOpts}</select></label><label>Canonical location<select id="teleLocation">${locations}</select></label><label>Reason<input id="teleReason" value="GM teleport"></label><button class="btn primary" id="teleportPlayer">Teleport</button></section>
  <section class="card control"><h3>💰 Grant Currency</h3><label>Player<select id="moneyPlayer">${pOpts}</select></label><label>Currency<select id="currency">${currencies}</select></label><label>Amount<input id="currencyAmount" type="number" min="1" value="100"></label><label>Reason<input id="currencyReason" value="GM reward"></label><button class="btn primary" id="grantCurrency">Grant</button></section>
  <section class="card control"><h3>☯ Karma Adjustment</h3><label>Player<select id="karmaPlayer">${pOpts}</select></label><label>Delta<input id="karmaDelta" type="number" value="10"></label><label>Reason<input id="karmaReason" value="GM correction"></label><button class="btn" id="adjustKarma">Adjust karma</button></section>
  <section class="card control dangerzone"><h3>❤️ Recovery</h3><p>Emergency character-state recovery.</p><label>Player<select id="recoverPlayer">${pOpts}</select></label><label>Reason<input id="recoverReason" value="GM recovery"></label><div class="buttonrow"><button class="btn danger" id="revivePlayer">Revive</button><button class="btn danger" id="clearBattle">Clear battle</button></div></section>
  <section class="card control"><h3>🤖 Automation</h3><p>Enable or disable persisted autonomous systems.</p><div class="toggle-list">${Object.entries(automation).map(([k,v])=>`<label class="toggle"><span>${esc(k)}</span><input type="checkbox" data-auto="${esc(k)}" ${v?'checked':''}></label>`).join('')}</div></section>
  <section class="card control dangerzone"><h3>🗄️ Database Maintenance</h3><p>Operations run inside the Go database service.</p><div class="buttonrow"><button class="btn" id="createBackup">Create backup</button><button class="btn" id="optimizeDb">Optimize</button><button class="btn danger" id="vacuumDb">VACUUM</button></div><h4>Backups</h4>${table([['Name','name'],['Size',r=>n(r.size)],['Created',r=>new Date(Number(r.modified_at)*1000).toLocaleString()]],d.backups||[])}</section>
 </div>
 <h2>Recent Admin Audit</h2>${table([['ID','audit_id'],['Action','action'],['Target','target'],['Reason','reason'],['When',r=>new Date(Number(r.created_at)*1000).toLocaleString()]],d.audit||[])}`;
 const out=document.getElementById('adminResult');
 const run=async(action,payload,confirmText='')=>{if(confirmText&&!confirm(confirmText))return;out.innerHTML='<div class="loading">Applying authoritative action…</div>';try{const r=await adminPost(action,payload);out.innerHTML=resultBox(r.result??r);setTimeout(()=>loadAdmin().catch(()=>{}),900)}catch(e){out.innerHTML=resultBox(e.message,false)}};
 advanceTime.onclick=()=>run('world.advance_time',{minutes:Number(timeMinutes.value),reason:timeReason.value},`Change canonical world time by ${timeMinutes.value} minutes?`);
 forceSim.onclick=()=>run('simulation.force',{system:simSystem.value,steps:Number(simSteps.value),reason:'GM dashboard forced simulation'},`Force ${simSystem.value} for ${simSteps.value} step(s)?`);
 setInterval.onclick=()=>run('simulation.interval',{system:simSystem.value,days:Number(simDays.value),reason:'GM dashboard interval change'});
 teleportPlayer.onclick=()=>run('player.teleport',{user_id:Number(telePlayer.value),location:teleLocation.value,reason:teleReason.value},'Teleport this player and reset their scene location?');
 grantCurrency.onclick=()=>run('player.grant_currency',{user_id:Number(moneyPlayer.value),currency_id:currency.value,amount:Number(currencyAmount.value),reason:currencyReason.value});
 adjustKarma.onclick=()=>run('player.karma',{user_id:Number(karmaPlayer.value),delta:Number(karmaDelta.value),reason:karmaReason.value});
 revivePlayer.onclick=()=>run('player.revive',{user_id:Number(recoverPlayer.value),reason:recoverReason.value},'Revive this character, refill Vitality/Qi, cancel Samsara, and clear active battles?');
 clearBattle.onclick=()=>run('player.clear_battle',{user_id:Number(recoverPlayer.value),reason:recoverReason.value},'Force-abandon all active battles for this player?');
 createBackup.onclick=()=>run('backup.create',{reason:'GM dashboard backup'});
 optimizeDb.onclick=()=>run('database.optimize',{reason:'GM dashboard optimize'});
 vacuumDb.onclick=()=>run('database.vacuum',{reason:'GM dashboard vacuum'},'VACUUM locks/rebuilds SQLite. Run it now?');
 document.querySelectorAll('[data-auto]').forEach(el=>el.onchange=()=>run('automation.set',{system:el.dataset.auto,enabled:el.checked,reason:'GM dashboard automation toggle'}));
}

const loaders={overview:loadOverview,timeline:loadTimeline,npcs:loadNPCs,families:loadFamilies,sects:loadSects,conflicts:loadConflicts,events:loadEvents,players:loadPlayers,rag:loadRag,decisions:loadDecisions,discord:loadDiscordSetup,admin:loadAdmin};
async function switchView(v){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));app.innerHTML='<div class="loading">Loading…</div>';try{await loaders[v]()}catch(e){app.innerHTML=`<div class="card"><h3>Dashboard error</h3><div class="bad">${esc(e.message)}</div></div>`}}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.getElementById('closeDrawer').onclick=()=>drawer.classList.add('hidden');drawer.onclick=e=>{if(e.target===drawer)drawer.classList.add('hidden')};switchView('overview');setInterval(()=>{if(document.querySelector('#nav button.active')?.dataset.view==='overview')loadOverview().catch(()=>{})},15000);
