"""The migration drill (v1.0.0-rc.1): a database from every shipped schema
migrates to current with no data loss.

For every schema version N the bot ever shipped, a database is bootstrapped
at N (the historical base schema plus the migrations up to N, exactly as a
release at N built it), a row is seeded into every table that will take
one, and the database is opened by the current release. The drill holds
that the schema lands on the current version, that every table present at
N is still present with every column it had, and that every seeded row is
still there. A migration that dropped a column or lost a row would fail
here before it reached a NAS.
"""
from __future__ import annotations

import json
import sqlite3
import tempfile
import unittest
from contextlib import closing
from pathlib import Path
from unittest.mock import patch

from tests.support import PROJECT_ROOT, install_aiosqlite_shim

install_aiosqlite_shim()

from app.database import Database, SCHEMA_VERSION
from app.database import core as database_core

# Tables the historical bootstrap or a migration rebuilds on purpose (a
# temporary or derived table), whose rows are not data. Empty today; a
# future migration that legitimately rebuilds a table names it here with
# the reason, so the drill stays honest about what it exempts.
# Tables a migration drops on purpose. The drill's rule is that nothing
# disappears silently, so an intentional removal is declared here with its
# reason rather than the assertion being loosened.
DROPPED_TABLES: dict[str, str] = {
    "core_request_log": (
        "migration 44: came in with 12 (versioned_core_write_ledger) and was "
        "never written and never read by anything, in any release since. The "
        "authority ledger that shipped is authoritative_actor_versions, "
        "authoritative_action_receipts and domain_events."
    ),
    "core_state_versions": "migration 44: the other half of the same unused ledger.",
}

REBUILT_TABLES: dict[str, str] = {
    # Migrations 20 (shared_starter_birth_households) and 22
    # (canonical_family_homeland_cities) clear the pending creation offers on
    # purpose: they are regenerated from the new household content the next
    # time a player opens /begin, and a stale offer would name a household
    # that no longer exists.
    "character_creation_family_options": "creation offers are cleared and regenerated by migrations 20 and 22",
}

DUMMY = {"INTEGER": 1, "INT": 1, "REAL": 0.5, "TEXT": "drill", "BLOB": b"x", "NUMERIC": 1, "BOOLEAN": 1}


def _columns(conn: sqlite3.Connection, table: str) -> list[tuple[str, str, int, object, int]]:
    return [(str(r[1]), str(r[2]).upper(), int(r[3]), r[4], int(r[5])) for r in conn.execute(f'PRAGMA table_info("{table}")')]


def _tables(conn: sqlite3.Connection) -> list[str]:
    return [str(r[0]) for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '%_fts%' ORDER BY name")]


def _seed(conn: sqlite3.Connection, table: str) -> bool:
    """Insert one row filling every NOT NULL column without a default with a
    typed dummy. Constraints the dummy cannot satisfy (a CHECK, a foreign
    key, a unique pair) mean the table is skipped, not failed - the drill
    is about what survives, and it seeds what it can."""
    cols = _columns(conn, table)
    if not cols:
        return False
    names, values = [], []
    for name, ctype, notnull, default, pk in cols:
        if pk and "INT" in ctype:
            continue  # rowid
        if notnull and default is None:
            base = next((v for key, v in DUMMY.items() if key in ctype), "drill")
            names.append(f'"{name}"')
            values.append(base)
    try:
        conn.execute(f'INSERT INTO "{table}"({",".join(names)}) VALUES({",".join("?" for _ in values)})' if names else f'INSERT INTO "{table}" DEFAULT VALUES', values)
        return True
    except sqlite3.Error:
        return False


class MigrationDrill(unittest.IsolatedAsyncioTestCase):
    async def _bootstrap_at(self, path: Path, version: int) -> None:
        migrations = tuple(m for m in database_core.SCHEMA_MIGRATIONS if int(m[0]) <= version)
        with patch.object(database_core, "SCHEMA_VERSION", version), patch.object(database_core, "SCHEMA_MIGRATIONS", migrations):
            await Database(path).init()

    async def test_every_shipped_schema_migrates_to_current_without_data_loss(self):
        self.assertEqual(SCHEMA_VERSION, database_core.SCHEMA_MIGRATIONS[-1][0])
        for version in range(1, SCHEMA_VERSION):
            with self.subTest(schema=version):
                with tempfile.TemporaryDirectory() as tmp:
                    path = Path(tmp) / f"schema-{version}.sqlite3"
                    await self._bootstrap_at(path, version)
                    with closing(sqlite3.connect(path)) as conn:
                        self.assertEqual(conn.execute("SELECT current_version FROM schema_version").fetchone()[0], version)
                        before = {t: _columns(conn, t) for t in _tables(conn)}
                        conn.execute("PRAGMA foreign_keys=OFF")
                        seeded = {}
                        for table in before:
                            if table in REBUILT_TABLES or table in DROPPED_TABLES or table in ("schema_version", "schema_migrations"):
                                continue
                            if _seed(conn, table):
                                seeded[table] = conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
                        conn.commit()
                    self.assertGreater(len(seeded), 20, "the drill should be seeding most tables")
                    db = Database(path)
                    await db.init()
                    status = await db.get_schema_status()
                    self.assertEqual(status["current"], SCHEMA_VERSION)
                    self.assertTrue(status["compatible"])
                    with closing(sqlite3.connect(path)) as conn:
                        after_tables = set(_tables(conn))
                        for table, cols in before.items():
                            if table in DROPPED_TABLES:
                                self.assertNotIn(table, after_tables,
                                                 f"schema {version}: {table} is declared dropped but survived")
                                continue
                            self.assertIn(table, after_tables, f"schema {version}: table {table} is gone after migrating")
                            after_cols = {c[0] for c in _columns(conn, table)}
                            for name, *_ in cols:
                                self.assertIn(name, after_cols, f"schema {version}: {table}.{name} is gone after migrating")
                        for table, count in seeded.items():
                            self.assertEqual(conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0], count, f"schema {version}: rows lost in {table}")
                        applied = [r[0] for r in conn.execute("SELECT version FROM schema_migrations ORDER BY version")]
                        self.assertEqual(applied, list(range(1, SCHEMA_VERSION + 1)))


if __name__ == "__main__":
    unittest.main()


class GrandfatheringDrill(unittest.IsolatedAsyncioTestCase):
    """Nobody loses a method they could already work (v1.0.0-rc.20).

    The learning step gates crafting on knowledge, and every character created
    before it existed knew nothing at all - so without this, the update would
    land as a takeaway on every live cultivator at once. Migration 46 credits
    each of them with every method their profession level already reaches.
    """

    async def _at(self, path: Path, version: int) -> None:
        migrations = tuple(m for m in database_core.SCHEMA_MIGRATIONS if int(m[0]) <= version)
        with patch.object(database_core, "SCHEMA_VERSION", version), patch.object(database_core, "SCHEMA_MIGRATIONS", migrations):
            await Database(path).init()

    async def test_an_existing_cultivator_keeps_what_their_level_reached(self):
        world = json.loads((PROJECT_ROOT / "content" / "world.json").read_text(encoding="utf-8"))
        recipes = world["recipes"]
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "grandfather.sqlite3"
            await self._at(path, 45)  # the release before the learning step

            with sqlite3.connect(path) as db:
                db.execute(
                    "INSERT INTO characters(user_id,discord_name,name,origin,path,spiritual_root,concept,"
                    "gender,location,attributes_json,created_at,updated_at) "
                    "VALUES(7,'d','Mid-Career','o','Sword Cultivator','Fire Root','c','neutral','Greenriver Town','{}',0,0)"
                )
                # An alchemist three levels in, and nothing else practised.
                db.execute(
                    "INSERT INTO profession_progress(user_id,profession,level,xp,updated_at) VALUES(7,'Alchemy',3,0,0)"
                )
                db.commit()

            await Database(path).init()  # forward to current, applying 46

            with sqlite3.connect(path) as db:
                known = {row[0] for row in db.execute("SELECT recipe FROM character_recipes WHERE user_id=7")}

        # Everything an Alchemy 3 could work the day before is still theirs...
        for name, recipe in recipes.items():
            if recipe["profession"] == "Alchemy" and int(recipe["min_level"]) <= 3:
                self.assertIn(name, known, f"{name} was taken away from a level-3 alchemist")
        # ...and the entry methods of every craft, which anyone could make.
        for name, recipe in recipes.items():
            if int(recipe["min_level"]) == 0:
                self.assertIn(name, known, f"{name} is an entry method and was taken away")
        # But not what they could never have worked anyway.
        for name, recipe in recipes.items():
            if recipe["profession"] == "Alchemy" and int(recipe["min_level"]) > 3:
                self.assertNotIn(name, known, f"{name} was handed to a level-3 alchemist who never had it")

    async def test_a_character_with_no_professions_still_keeps_the_entry_methods(self):
        world = json.loads((PROJECT_ROOT / "content" / "world.json").read_text(encoding="utf-8"))
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "grandfather-novice.sqlite3"
            await self._at(path, 45)
            with sqlite3.connect(path) as db:
                db.execute(
                    "INSERT INTO characters(user_id,discord_name,name,origin,path,spiritual_root,concept,"
                    "gender,location,attributes_json,created_at,updated_at) "
                    "VALUES(8,'d','Never Crafted','o','Sword Cultivator','Fire Root','c','neutral','Greenriver Town','{}',0,0)"
                )
                db.commit()
            await Database(path).init()
            with sqlite3.connect(path) as db:
                known = {row[0] for row in db.execute("SELECT recipe FROM character_recipes WHERE user_id=8")}
        entry = {n for n, r in world["recipes"].items() if int(r["min_level"]) == 0}
        self.assertEqual(known, entry, "a cultivator who never crafted should keep exactly the entry methods")
